# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = datastructure
DESTDIR = ./debug
CONFIG += debug console
DEFINES += QT_LARGEFILE_SUPPORT
INCLUDEPATH += . \
    ./test
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(datastructure.pri)
